name: Run Python Script and Push to Another Repo

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Monaco Font
        run: |
          sudo mkdir -p /usr/share/fonts/truetype/custom
          sudo cp fonts/Monaco.ttf /usr/share/fonts/truetype/custom
          sudo fc-cache -f -v

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}

      - name: Checkout 'adeshpande03' repository
        uses: actions/checkout@v2
        with:
          repository: adeshpande03/adeshpande03
          token: ${{ secrets.README_PAT }}
          path: "adeshpande03"

      - name: Copy points_graph.png to 'adeshpande03' repository
        run: |
          cp points_graph_rounded_corners.png adeshpande03/
          cp logs.log adeshpande03/

      - name: Commit and push to 'adeshpande03' repository
        run: |
          cd adeshpande03
          git config --global user.name 'Akhil Deshpande'
          git config --global user.email 'deshpande.akhil.s@gmail.com'
          git add points_graph_rounded_corners.png
          git add logs.log
          git commit -m "Update points_graph_rounded_corners.png"
          git push
            
      - name: Checkout 'Leetcode-Points-Graph' repository
        uses: actions/checkout@v2
        with:
          repository: adeshpande03/Leetcode-Points-Graph
          token: ${{ secrets.README_PAT }}
          path: "Leetcode-Points-Graph"

      - name: Copy points_graph.png to 'Leetcode-Points-Graph' repository
        run: |
          cp points_graph_rounded_corners.png Leetcode-Points-Graph/
          cp logs.log Leetcode-Points-Graph/

      - name: Commit and push to 'adeshpande03' repository
        run: |
          cd Leetcode-Points-Graph
          git config --global user.name 'Akhil Deshpande'
          git config --global user.email 'deshpande.akhil.s@gmail.com'
          git pull
          git add points_graph_rounded_corners.png
          git add logs.log
          git commit -m "Update points_graph_rounded_corners.png"
          git push